import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Add Employee' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('manju');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('n');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('gowda');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('04212');
  await page.locator('form span').click();
  await page.locator('div:nth-child(4) > .oxd-grid-2 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('Manju');
  await page.locator('input[type="password"]').first().click();
  await page.locator('input[type="password"]').first().fill('Sree@123');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).fill('Sree@123');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/219');
  await page.getByRole('link', { name: 'Contact Details' }).click();
  await page.locator('div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').fill('s rangapuram');
  await page.locator('div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').fill('amarapuarm');
  await page.locator('div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').fill('anantapuram');
  await page.locator('div:nth-child(4) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('adnrapradesh');
  //await page.getByText('-- Select --').click();
  await page.locator('form i').click();
  await page.locator('form i').click();
  //await page.getByRole('option', { name: 'India', exact: true }).click();
  await page.locator('div:nth-child(5) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('515286');
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').first().click();
  await page.locator('.oxd-input.oxd-input--focus').fill('94918282');
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('33488665473');
  await page.locator('div:nth-child(6) > .oxd-grid-3 > div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('8877553392');
  await page.getByRole('button', { name: 'Save' }).click();
  //await page.getByRole('listitem').filter({ hasText: 'manda user' }).locator('i').click();
  //await page.getByRole('menuitem', { name: 'Logout' }).click();
});